[package]
name = "posterize"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
image = "0.25.0"
itertools = "0.13.0"
rand = "0.8.5"
rayon = "1.10.0"
thread_local = "1.1.8"
