[package]
name = "cluster"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
itertools = "0.13.0"
math = { version = "0.1.0", path = "../math" }
rand = "0.8.5"
