[package]
name = "cluster-visualizer"
version = "0.1.0"
edition = "2021"

[dependencies]
cluster = { version = "0.1.0", path = "../cluster" }
itertools = "0.13.0"
rand = "0.8.5"
rand_distr = "0.4.3"
sdl2 = "0.36.0"
